### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/zapfilter#12]
* [x] custom filter (#2)
* [x] filter by level (#2)
* [x] filter by namespace (#2)
* [x] implement simple `ParseRules` helper (#5)
* [x] support various level formats: `info`, `info+`, `*` (#6, #8) 
* [x] zap wrapper (#7)
* [x] add helpers to check if a log is filtered or not (#9)
* [x] add examples in README (#10, #13)
* [x] support exclude (#11)
* [x] replace map with binary mask and use iotas (#13)
* [x] add doc about levels (info, info+, etc) (#13)
* [ ] support `@` in filters
* [ ] add links to repos using it in README
* [ ] add link to this repo on official zap doc
